INSERT INTO elements (name) VALUES
  ( 'Acid Rain' ),
  ( 'Air' ),
  ( 'Airplane' ),
  ( 'Alarm Clock' ),
  ( 'Alchemist' ),
  ( 'Alcohol' ),
  ( 'Algae' ),
  ( 'Alien' ),
  ( 'Allergy' ),
  ( 'Alligator' ),
  ( 'Alpaca' ),
  ( 'Ambulance' ),
  ( 'Angel' ),
  ( 'Angler' ),
  ( 'Animal' ),
  ( 'Ant' ),
  ( 'Ant Farm' ),
  ( 'Antarctica' ),
  ( 'Anthill' ),
  ( 'Apron' ),
  ( 'Aquarium' ),
  ( 'Archeologist' ),
  ( 'Archipelago' ),
  ( 'Arctic' ),
  ( 'Armadillo' ),
  ( 'Armor' ),
  ( 'Arrow' ),
  ( 'Ash' ),
  ( 'Astronaut' ),
  ( 'Atmosphere' ),
  ( 'Atomic Bomb' ),
  ( 'Aurora' ),
  ( 'Avalanche' ),
  ( 'Axe' ),
  ( 'Bacon' ),
  ( 'Bacteria' ),
  ( 'Baker' ),
  ( 'Bakery' ),
  ( 'Banana' ),
  ( 'Banana Bread' ),
  ( 'Bandage' ),
  ( 'Bank' ),
  ( 'Barn' ),
  ( 'Bat' ),
  ( 'Batter' ),
  ( 'Battery' ),
  ( 'Bayonet' ),
  ( 'BBQ' ),
  ( 'Beach' ),
  ( 'Beaver' ),
  ( 'Bee' ),
  ( 'Beehive' ),
  ( 'Beekeeper' ),
  ( 'Beer' ),
  ( 'Bell' ),
  ( 'Bicycle' ),
  ( 'Big' ),
  ( 'Bird' ),
  ( 'Birdcage' ),
  ( 'Birdhouse' ),
  ( 'Black Hole' ),
  ( 'Blade' ),
  ( 'Blender' ),
  ( 'Blizzard' ),
  ( 'Blood' ),
  ( 'Blood Bag' ),
  ( 'Boat' ),
  ( 'Boiler' ),
  ( 'Bone' ),
  ( 'Bonsai Tree' ),
  ( 'Book' ),
  ( 'Bottle' ),
  ( 'Boulder' ),
  ( 'Bow' ),
  ( 'Box' ),
  ( 'Bread' ),
  ( 'Brick' ),
  ( 'Bridge' ),
  ( 'Broom' ),
  ( 'Bucket' ),
  ( 'Bullet' ),
  ( 'Bulletproof Vest' ),
  ( 'Bus' ),
  ( 'Butcher' ),
  ( 'Butter' ),
  ( 'Butterfly' ),
  ( 'Butterfly Net' ),
  ( 'Cable Car' ),
  ( 'Cactus' ),
  ( 'Cage' ),
  ( 'Cake' ),
  ( 'Camel' ),
  ( 'Campfire' ),
  ( 'Candle' ),
  ( 'Candy Cane' ),
  ( 'Cannon' ),
  ( 'Canvas' ),
  ( 'Car' ),
  ( 'Caramel' ),
  ( 'Carbon Dioxide' ),
  ( 'Carrot' ),
  ( 'Cart' ),
  ( 'Cashmere' ),
  ( 'Castle' ),
  ( 'Cat' ),
  ( 'Catnip' ),
  ( 'Cauldron' ),
  ( 'Cave' ),
  ( 'Caviar' ),
  ( 'Centaur' ),
  ( 'Cereal' ),
  ( 'Chain' ),
  ( 'Chainsaw' ),
  ( 'Chameleon' ),
  ( 'Charcoal' ),
  ( 'Cheese' ),
  ( 'Cheeseburger' ),
  ( 'Chicken' ),
  ( 'Chicken Coop' ),
  ( 'Chicken Soup' ),
  ( 'Chicken wing' ),
  ( 'Chill' ),
  ( 'Chimney' ),
  ( 'Chocolate' ),
  ( 'Chocolate Milk' ),
  ( 'Christmas Stocking' ),
  ( 'Christmas Tree' ),
  ( 'Cigarette' ),
  ( 'City' ),
  ( 'Clay' ),
  ( 'Clock' ),
  ( 'Closet' ),
  ( 'Cloud' ),
  ( 'Coal' ),
  ( 'Coconut' ),
  ( 'Coconut Milk' ),
  ( 'Coffin' ),
  ( 'Cold' ),
  ( 'Combustion Engine' ),
  ( 'Computer' ),
  ( 'Computer Mouse' ),
  ( 'Confetti' ),
  ( 'Constellation' ),
  ( 'Container' ),
  ( 'Continent' ),
  ( 'Cook' ),
  ( 'Cookbook' ),
  ( 'Cookie' ),
  ( 'Cookie Cutter' ),
  ( 'Cookie Dough' ),
  ( 'Coral' ),
  ( 'Corpse' ),
  ( 'Cotton' ),
  ( 'Cotton Candy' ),
  ( 'Cow' ),
  ( 'Crayon' ),
  ( 'Crow' ),
  ( 'Crystal Ball' ),
  ( 'Cuckoo' ),
  ( 'Cup' ),
  ( 'Current' ),
  ( 'Cutting Board' ),
  ( 'Cyborg' ),
  ( 'Cyclist' ),
  ( 'Dam' ),
  ( 'Darkness' ),
  ( 'Dawn' ),
  ( 'Day' ),
  ( 'Death' ),
  ( 'Desert' ),
  ( 'Dew' ),
  ( 'Diamond' ),
  ( 'Dinosaur' ),
  ( 'Diver' ),
  ( 'Doctor' ),
  ( 'Dog' ),
  ( 'Doge' ),
  ( 'Doghouse' ),
  ( 'Domestication' ),
  ( 'Don Quixote' ),
  ( 'Donut' ),
  ( 'Double Rainbow!' ),
  ( 'Dough' ),
  ( 'Dragon' ),
  ( 'Drone' ),
  ( 'Drum' ),
  ( 'Drunk' ),
  ( 'Dry Ice' ),
  ( 'Duck' ),
  ( 'Duckling' ),
  ( 'Dune' ),
  ( 'Dust' ),
  ( 'Dynamite' ),
  ( 'Eagle' ),
  ( 'Earth' ),
  ( 'Earthquake' ),
  ( 'Eclipse' ),
  ( 'Egg' ),
  ( 'Egg Timer' ),
  ( 'Electric Car' ),
  ( 'Electric Eel' ),
  ( 'Electrician' ),
  ( 'Electricity' ),
  ( 'Email' ),
  ( 'Energy' ),
  ( 'Engineer' ),
  ( 'Eruption' ),
  ( 'Excalibur' ),
  ( 'Explosion' ),
  ( 'Fabric' ),
  ( 'Fairy Tale' ),
  ( 'Family' ),
  ( 'Family tree' ),
  ( 'Farm' ),
  ( 'Farmer' ),
  ( 'Faun' ),
  ( 'Fence' ),
  ( 'Field' ),
  ( 'Fire' ),
  ( 'Fire Extinguisher' ),
  ( 'Firefighter' ),
  ( 'Fireplace' ),
  ( 'Firestation' ),
  ( 'Firetruck' ),
  ( 'Fireworks' ),
  ( 'Fish' ),
  ( 'Fishing Rod' ),
  ( 'Flamethrower' ),
  ( 'Flashlight' ),
  ( 'Flood' ),
  ( 'Flour' ),
  ( 'Flower' ),
  ( 'Flute' ),
  ( 'Flying Fish' ),
  ( 'Flying Squirrel' ),
  ( 'Fog' ),
  ( 'Force Knight' ),
  ( 'Forest' ),
  ( 'Fortune Cookie' ),
  ( 'Fossil' ),
  ( 'Fountain' ),
  ( 'Fox' ),
  ( 'Frankenstein’s Monster' ),
  ( 'French Fries' ),
  ( 'Fridge' ),
  ( 'Frog' ),
  ( 'Frozen Yogurt' ),
  ( 'Fruit' ),
  ( 'Fruit Tree' ),
  ( 'Galaxy' ),
  ( 'Galaxy Cluster' ),
  ( 'Garage' ),
  ( 'Garden' ),
  ( 'Gardener' ),
  ( 'Gas' ),
  ( 'Geyser' ),
  ( 'Ghost' ),
  ( 'Gift' ),
  ( 'Gingerbread House' ),
  ( 'Gingerbread Man' ),
  ( 'Glacier' ),
  ( 'Glass' ),
  ( 'Glasses' ),
  ( 'Gnome' ),
  ( 'Goat' ),
  ( 'Gold' ),
  ( 'Golem' ),
  ( 'Granite' ),
  ( 'Grass' ),
  ( 'Grave' ),
  ( 'Gravestone' ),
  ( 'Graveyard' ),
  ( 'Greenhouse' ),
  ( 'Grenade' ),
  ( 'Grilled Cheese' ),
  ( 'Grim Reaper' ),
  ( 'Gun' ),
  ( 'Gunpowder' ),
  ( 'Gust' ),
  ( 'Hacker' ),
  ( 'Hail' ),
  ( 'Ham' ),
  ( 'Hamburger' ),
  ( 'Hammer' ),
  ( 'Hamster' ),
  ( 'Hangar' ),
  ( 'Harp' ),
  ( 'Hay' ),
  ( 'Hay Bale' ),
  ( 'Heat' ),
  ( 'Hedge' ),
  ( 'Hedgehog' ),
  ( 'Helicopter' ),
  ( 'Hero' ),
  ( 'Hill' ),
  ( 'Hippo' ),
  ( 'Honey' ),
  ( 'Horizon' ),
  ( 'Horse' ),
  ( 'Horseshoe' ),
  ( 'Hospital' ),
  ( 'Hot Chocolate' ),
  ( 'Hourglass' ),
  ( 'House' ),
  ( 'Human' ),
  ( 'Hummingbird' ),
  ( 'Hurricane' ),
  ( 'Husky' ),
  ( 'Ice' ),
  ( 'Ice Cream' ),
  ( 'Ice Cream Truck' ),
  ( 'Ice Sculpture' ),
  ( 'Iceberg' ),
  ( 'Iced Tea' ),
  ( 'Idea' ),
  ( 'Igloo' ),
  ( 'Internet' ),
  ( 'Island' ),
  ( 'Ivy' ),
  ( 'Jack-O-Lantern' ),
  ( 'Jam' ),
  ( 'Jar' ),
  ( 'Jerky' ),
  ( 'Juice' ),
  ( 'Jupiter' ),
  ( 'Kaiju' ),
  ( 'Katana' ),
  ( 'Kite' ),
  ( 'Knife' ),
  ( 'Knight' ),
  ( 'Lake' ),
  ( 'Lamp' ),
  ( 'Land' ),
  ( 'Lasso' ),
  ( 'Lava' ),
  ( 'Lava Lamp' ),
  ( 'Lawn' ),
  ( 'Lawn Mower' ),
  ( 'Leaf' ),
  ( 'Leather' ),
  ( 'Legend' ),
  ( 'Lens' ),
  ( 'Letter' ),
  ( 'Librarian' ),
  ( 'Library' ),
  ( 'Life' ),
  ( 'Light' ),
  ( 'Light Bulb' ),
  ( 'Light Sword' ),
  ( 'Lighthouse' ),
  ( 'Lightning' ),
  ( 'Lion' ),
  ( 'Liquid' ),
  ( 'Little Alchemy' ),
  ( 'Livestock' ),
  ( 'Lizard' ),
  ( 'Log cabin' ),
  ( 'Love' ),
  ( 'Lumberjack' ),
  ( 'Mac and Cheese' ),
  ( 'Machine' ),
  ( 'Magic' ),
  ( 'Magma' ),
  ( 'Mailbox' ),
  ( 'Mailman' ),
  ( 'Manatee' ),
  ( 'Map' ),
  ( 'Maple Syrup' ),
  ( 'Mars' ),
  ( 'Marshmallows' ),
  ( 'Mayonnaise' ),
  ( 'Meat' ),
  ( 'Medusa' ),
  ( 'Mercury' ),
  ( 'Mermaid' ),
  ( 'Metal' ),
  ( 'Meteor' ),
  ( 'Meteoroid' ),
  ( 'Microscope' ),
  ( 'Milk' ),
  ( 'Milk Shake' ),
  ( 'Mineral' ),
  ( 'Minotaur' ),
  ( 'Mirror' ),
  ( 'Mist' ),
  ( 'Mold' ),
  ( 'Monarch' ),
  ( 'Money' ),
  ( 'Monkey' ),
  ( 'Moon' ),
  ( 'Moon Rover' ),
  ( 'Moss' ),
  ( 'Moth' ),
  ( 'Motion' ),
  ( 'Motorcycle' ),
  ( 'Mountain' ),
  ( 'Mountain Goat' ),
  ( 'Mountain Range' ),
  ( 'Mouse' ),
  ( 'Mousetrap' ),
  ( 'Mud' ),
  ( 'Mummy' ),
  ( 'Music' ),
  ( 'Musician' ),
  ( 'Narwhal' ),
  ( 'Needle' ),
  ( 'Nessie' ),
  ( 'Nest' ),
  ( 'Net' ),
  ( 'Newspaper' ),
  ( 'Night' ),
  ( 'Ninja' ),
  ( 'Ninja Turtle' ),
  ( 'Nuts' ),
  ( 'Oasis' ),
  ( 'Obsidian' ),
  ( 'Ocean' ),
  ( 'Oil' ),
  ( 'Omelette' ),
  ( 'Optical Fiber' ),
  ( 'Orchard' ),
  ( 'Ore' ),
  ( 'Organic Matter' ),
  ( 'Origami' ),
  ( 'Ostrich' ),
  ( 'Owl' ),
  ( 'Oxygen' ),
  ( 'Ozone' ),
  ( 'Paint' ),
  ( 'Painter' ),
  ( 'Painting' ),
  ( 'Paleontologist' ),
  ( 'Palm' ),
  ( 'Pan Flute' ),
  ( 'Paper' ),
  ( 'Paper Airplane' ),
  ( 'Paper Cup' ),
  ( 'Parachute' ),
  ( 'Park' ),
  ( 'Parrot' ),
  ( 'Pasta' ),
  ( 'Peacock' ),
  ( 'Peanut Butter' ),
  ( 'Peat' ),
  ( 'Pebble' ),
  ( 'Pegasus' ),
  ( 'Pencil' ),
  ( 'Pencil Sharpener' ),
  ( 'Penguin' ),
  ( 'Penicillin' ),
  ( 'Perfume' ),
  ( 'Petroleum' ),
  ( 'Philosophy' ),
  ( 'Phoenix' ),
  ( 'Picnic' ),
  ( 'Pie' ),
  ( 'Pig' ),
  ( 'Pigeon' ),
  ( 'Piggy Bank' ),
  ( 'Pilot' ),
  ( 'Pinocchio' ),
  ( 'Pipe' ),
  ( 'Piranha' ),
  ( 'Pirate' ),
  ( 'Pirate Ship' ),
  ( 'Pitchfork' ),
  ( 'Pizza' ),
  ( 'Planet' ),
  ( 'Plankton' ),
  ( 'Plant' ),
  ( 'Plasma' ),
  ( 'Platypus' ),
  ( 'Plow' ),
  ( 'Polar Bear' ),
  ( 'Pollen' ),
  ( 'Pond' ),
  ( 'Popsicle' ),
  ( 'Post Office' ),
  ( 'Potato' ),
  ( 'Potter' ),
  ( 'Pottery' ),
  ( 'Pressure' ),
  ( 'Primordial Soup' ),
  ( 'Printer' ),
  ( 'Prism' ),
  ( 'Pterodactyl' ),
  ( 'Puddle' ),
  ( 'Pumpkin' ),
  ( 'Pyramid' ),
  ( 'Quicksand' ),
  ( 'Quicksilver' ),
  ( 'Rabbit' ),
  ( 'Rain' ),
  ( 'Rainbow' ),
  ( 'Rainforest' ),
  ( 'Rat' ),
  ( 'Recipe' ),
  ( 'Reed' ),
  ( 'Reindeer' ),
  ( 'Ring' ),
  ( 'River' ),
  ( 'Rivulet' ),
  ( 'Robot' ),
  ( 'Robot Vacuum' ),
  ( 'Rock' ),
  ( 'Rocket' ),
  ( 'Roe' ),
  ( 'Roller Coaster' ),
  ( 'Rope' ),
  ( 'Rose' ),
  ( 'Ruins' ),
  ( 'Ruler' ),
  ( 'Rust' ),
  ( 'RV' ),
  ( 'Sack' ),
  ( 'Saddle' ),
  ( 'Safe' ),
  ( 'Safety Glasses' ),
  ( 'Sailboat' ),
  ( 'Sailor' ),
  ( 'Salt' ),
  ( 'Sand' ),
  ( 'Sand Castle' ),
  ( 'Sandpaper' ),
  ( 'Sandstone' ),
  ( 'Sandstorm' ),
  ( 'Sandwich' ),
  ( 'Santa' ),
  ( 'Sap' ),
  ( 'Saturn' ),
  ( 'Scalpel' ),
  ( 'Scarecrow' ),
  ( 'Science' ),
  ( 'Scissors' ),
  ( 'Scorpion' ),
  ( 'Scuba Tank' ),
  ( 'Scythe' ),
  ( 'Sea' ),
  ( 'Seagull' ),
  ( 'Seahorse' ),
  ( 'Seal' ),
  ( 'Seaplane' ),
  ( 'Seasickness' ),
  ( 'Seaweed' ),
  ( 'Seed' ),
  ( 'Sewing Machine' ),
  ( 'Shark' ),
  ( 'Sheep' ),
  ( 'Sheet Music' ),
  ( 'Shovel' ),
  ( 'Shuriken' ),
  ( 'Sickness' ),
  ( 'Silo' ),
  ( 'Skateboard' ),
  ( 'Skeleton' ),
  ( 'Ski Goggles' ),
  ( 'Skier' ),
  ( 'Sky' ),
  ( 'Skyscraper' ),
  ( 'Sleigh' ),
  ( 'Sloth' ),
  ( 'Small' ),
  ( 'Smog' ),
  ( 'Smoke' ),
  ( 'Smoke Signal' ),
  ( 'Smoothie' ),
  ( 'Snake' ),
  ( 'Snow' ),
  ( 'Snow Globe' ),
  ( 'Snowball' ),
  ( 'Snowboard' ),
  ( 'Snowman' ),
  ( 'Snowmobile' ),
  ( 'Soap' ),
  ( 'Soda' ),
  ( 'Soil' ),
  ( 'Solar Cell' ),
  ( 'Solar System' ),
  ( 'Solid' ),
  ( 'Sound' ),
  ( 'Space' ),
  ( 'Space Station' ),
  ( 'Spaceship' ),
  ( 'Spaghetti' ),
  ( 'Sphinx' ),
  ( 'Spider' ),
  ( 'Spotlight' ),
  ( 'Sprinkles' ),
  ( 'Squirrel' ),
  ( 'Star' ),
  ( 'Starfish' ),
  ( 'Statue' ),
  ( 'Steak' ),
  ( 'Steam' ),
  ( 'Steam Engine' ),
  ( 'Steamboat' ),
  ( 'Steel' ),
  ( 'Steel Wool' ),
  ( 'Stethoscope' ),
  ( 'Stone' ),
  ( 'Storm' ),
  ( 'Story' ),
  ( 'Stream' ),
  ( 'String Phone' ),
  ( 'Stun Gun' ),
  ( 'Sugar' ),
  ( 'Sun' ),
  ( 'Sundial' ),
  ( 'Sunflower' ),
  ( 'Sunglasses' ),
  ( 'Supernova' ),
  ( 'Surfer' ),
  ( 'Sushi' ),
  ( 'Swamp' ),
  ( 'Sweater' ),
  ( 'Swim Goggles' ),
  ( 'Swimmer' ),
  ( 'Swimming Pool' ),
  ( 'Sword' ),
  ( 'Swordfish' ),
  ( 'Syringe' ),
  ( 'Tank' ),
  ( 'Tea' ),
  ( 'Telescope' ),
  ( 'Tent' ),
  ( 'The One Ring' ),
  ( 'Thermometer' ),
  ( 'Thread' ),
  ( 'Tide' ),
  ( 'Time' ),
  ( 'Titanic' ),
  ( 'Toast' ),
  ( 'Tobacco' ),
  ( 'Tool' ),
  ( 'Toolbox' ),
  ( 'Tornado' ),
  ( 'Toucan' ),
  ( 'Tractor' ),
  ( 'Train' ),
  ( 'Trainyard' ),
  ( 'Treasure' ),
  ( 'Treasure Map' ),
  ( 'Tree' ),
  ( 'Treehouse' ),
  ( 'Trojan Horse' ),
  ( 'Tsunami' ),
  ( 'Tunnel' ),
  ( 'Turtle' ),
  ( 'Twilight' ),
  ( 'Tyrannosaurus Rex' ),
  ( 'UFO' ),
  ( 'Umbrella' ),
  ( 'Unicorn' ),
  ( 'Universe' ),
  ( 'Vacuum Cleaner' ),
  ( 'Vampire' ),
  ( 'Vase' ),
  ( 'Vault' ),
  ( 'Vegetable' ),
  ( 'Venus' ),
  ( 'Village' ),
  ( 'Vine' ),
  ( 'Vinegar' ),
  ( 'Volcano' ),
  ( 'Vulture' ),
  ( 'Wagon' ),
  ( 'Wall' ),
  ( 'Wand' ),
  ( 'Warmth' ),
  ( 'Warrior' ),
  ( 'Watch' ),
  ( 'Water' ),
  ( 'Water Gun' ),
  ( 'Water Lily' ),
  ( 'Water Pipe' ),
  ( 'Waterfall' ),
  ( 'Wave' ),
  ( 'Wax' ),
  ( 'Web' ),
  ( 'Werewolf' ),
  ( 'Wheat' ),
  ( 'Wheel' ),
  ( 'Wild Boar' ),
  ( 'Wind' ),
  ( 'Wind Turbine' ),
  ( 'Windmill' ),
  ( 'Windsurfer' ),
  ( 'Wine' ),
  ( 'Wire' ),
  ( 'Witch' ),
  ( 'Wizard' ),
  ( 'Wolf' ),
  ( 'Wood' ),
  ( 'Woodpecker' ),
  ( 'Wool' ),
  ( 'Wrapping Paper' ),
  ( 'Yeti' ),
  ( 'Yogurt' ),
  ( 'Zombie' ),
  ( 'Zoo' )
;
