INSERT INTO elements (name) VALUES
  ( "Achilles" ),
  ( "Acid Rain" ),
  ( "Aegis" ),
  ( "Aeolus" ),
  ( "Airplane" ),
  ( "Alarm Clock" ),
  ( "Alchemist" ),
  ( "Alcohol" ),
  ( "Algae" ),
  ( "Alien" ),
  ( "Allergy" ),
  ( "Alligator" ),
  ( "Alpaca" ),
  ( "Ambulance" ),
  ( "Angel" ),
  ( "Angler" ),
  ( "Animal" ),
  ( "Ankh" ),
  ( "Ant" ),
  ( "Ant Farm" ),
  ( "Antarctica" ),
  ( "Anthill" ),
  ( "Apple of Discord" ),
  ( "Apron" ),
  ( "Aquarium" ),
  ( "Archeologist" ),
  ( "Archipelago" ),
  ( "Arctic" ),
  ( "Armadillo" ),
  ( "Armor" ),
  ( "Arrow" ),
  ( "Ash" ),
  ( "Astronaut" ),
  ( "Astronomer" ),
  ( "Atmosphere" ),
  ( "Atomic Bomb" ),
  ( "Aurora" ),
  ( "Avalanche" ),
  ( "Aviary" ),
  ( "Axe" ),
  ( "Baast" ),
  ( "Baba Yaga" ),
  ( "Babe the Blue Ox" ),
  ( "Bacon" ),
  ( "Bacteria" ),
  ( "Baker" ),
  ( "Bakery" ),
  ( "Banana" ),
  ( "Banana Bread" ),
  ( "Bandage" ),
  ( "Bank" ),
  ( "Banshee" ),
  ( "Barn" ),
  ( "Barrel" ),
  ( "Bat" ),
  ( "Batter" ),
  ( "Battery" ),
  ( "Bayonet" ),
  ( "Bbq" ),
  ( "Beach" ),
  ( "Beaver" ),
  ( "Bee" ),
  ( "Beehive" ),
  ( "Beekeeper" ),
  ( "Beer" ),
  ( "Bell" ),
  ( "Bicycle" ),
  ( "Binoculars" ),
  ( "Bird" ),
  ( "Birdcage" ),
  ( "Birdhouse" ),
  ( "Black Hole" ),
  ( "Blade" ),
  ( "Blender" ),
  ( "Blizzard" ),
  ( "Blood" ),
  ( "Blood Bag" ),
  ( "Boat" ),
  ( "Boiler" ),
  ( "Bone" ),
  ( "Bonsai Tree" ),
  ( "Book" ),
  ( "Book of the Dead" ),
  ( "Bottle" ),
  ( "Boulder" ),
  ( "Bow" ),
  ( "Box" ),
  ( "Bread" ),
  ( "Brick" ),
  ( "Bridge" ),
  ( "Broom" ),
  ( "Bucket" ),
  ( "Bullet" ),
  ( "Bulletproof Vest" ),
  ( "Bunyip" ),
  ( "Bus" ),
  ( "Butcher" ),
  ( "Butter" ),
  ( "Butterfly" ),
  ( "Butterfly Net" ),
  ( "Cable Car" ),
  ( "Cactus" ),
  ( "Cage" ),
  ( "Cake" ),
  ( "Calydonian Boar" ),
  ( "Camazotz" ),
  ( "Camel" ),
  ( "Campfire" ),
  ( "Candle" ),
  ( "Candy Cane" ),
  ( "Cannon" ),
  ( "Canvas" ),
  ( "Car" ),
  ( "Caramel" ),
  ( "Carbon Dioxide" ),
  ( "Carrot" ),
  ( "Cart" ),
  ( "Cashmere" ),
  ( "Castle" ),
  ( "Cat" ),
  ( "Catnip" ),
  ( "Cauldron" ),
  ( "Cave" ),
  ( "Caviar" ),
  ( "Centaur" ),
  ( "Cereal" ),
  ( "Chain" ),
  ( "Chainsaw" ),
  ( "Chameleon" ),
  ( "Chang'e" ),
  ( "Changeling" ),
  ( "Charcoal" ),
  ( "Cheese" ),
  ( "Cheeseburger" ),
  ( "Chicken" ),
  ( "Chicken Coop" ),
  ( "Chicken Soup" ),
  ( "Chicken Wing" ),
  ( "Chill" ),
  ( "Chimera" ),
  ( "Chimney" ),
  ( "Chinese Dragon" ),
  ( "Chocolate" ),
  ( "Chocolate Milk" ),
  ( "Christmas Stocking" ),
  ( "Christmas Tree" ),
  ( "Cigarette" ),
  ( "Circus" ),
  ( "City" ),
  ( "Clay" ),
  ( "Clock" ),
  ( "Closet" ),
  ( "Cloud" ),
  ( "Coal" ),
  ( "Cockatrice" ),
  ( "Coconut" ),
  ( "Coconut Milk" ),
  ( "Coffin" ),
  ( "Cold" ),
  ( "Combustion Engine" ),
  ( "Computer" ),
  ( "Computer Mouse" ),
  ( "Confetti" ),
  ( "Constellation" ),
  ( "Continent" ),
  ( "Cook" ),
  ( "Cookbook" ),
  ( "Cookie" ),
  ( "Cookie Cutter" ),
  ( "Cookie Dough" ),
  ( "Coral" ),
  ( "Corpse" ),
  ( "Cosmic Egg" ),
  ( "Cotton" ),
  ( "Cotton Candy" ),
  ( "Cow" ),
  ( "Crayon" ),
  ( "Crow" ),
  ( "Crystal Ball" ),
  ( "Cthulhu" ),
  ( "Cuckoo" ),
  ( "Cup" ),
  ( "Cupid" ),
  ( "Current" ),
  ( "Curse" ),
  ( "Cutting Board" ),
  ( "Cyborg" ),
  ( "Cyclist" ),
  ( "Cyclops" ),
  ( "Dam" ),
  ( "Darkness" ),
  ( "Dawn" ),
  ( "Day" ),
  ( "Death" ),
  ( "Deity" ),
  ( "Demon" ),
  ( "Desert" ),
  ( "Dew" ),
  ( "Diamond" ),
  ( "Dinosaur" ),
  ( "Dionysus" ),
  ( "Diver" ),
  ( "Djinn" ),
  ( "Doctor" ),
  ( "Dog" ),
  ( "Doge" ),
  ( "Doghouse" ),
  ( "Domestication" ),
  ( "Domovoi" ),
  ( "Don Quixote" ),
  ( "Donut" ),
  ( "Double Rainbow!" ),
  ( "Dough" ),
  ( "Dragon" ),
  ( "Drone" ),
  ( "Drum" ),
  ( "Drunk" ),
  ( "Dry Ice" ),
  ( "Dryad" ),
  ( "Duck" ),
  ( "Duckling" ),
  ( "Dune" ),
  ( "Durendal" ),
  ( "Dust" ),
  ( "Dynamite" ),
  ( "Eagle" ),
  ( "Earthquake" ),
  ( "Eclipse" ),
  ( "Egg" ),
  ( "Egg Timer" ),
  ( "Electric Car" ),
  ( "Electric Eel" ),
  ( "Electrician" ),
  ( "Electricity" ),
  ( "Elf" ),
  ( "Elixir of Life" ),
  ( "Email" ),
  ( "Energy" ),
  ( "Engineer" ),
  ( "Epona" ),
  ( "Eruption" ),
  ( "Excalibur" ),
  ( "Excavator" ),
  ( "Explosion" ),
  ( "Fabric" ),
  ( "Factory" ),
  ( "Faerie" ),
  ( "Fairy Tale" ),
  ( "Family" ),
  ( "Family Tree" ),
  ( "Farm" ),
  ( "Farmer" ),
  ( "Father Time" ),
  ( "Faun" ),
  ( "Fence" ),
  ( "Fenrir" ),
  ( "Field" ),
  ( "Fire Extinguisher" ),
  ( "Firefighter" ),
  ( "Fireplace" ),
  ( "Firestation" ),
  ( "Firetruck" ),
  ( "Firewall" ),
  ( "Fireworks" ),
  ( "Fish" ),
  ( "Fishing Rod" ),
  ( "Flamethrower" ),
  ( "Flashlight" ),
  ( "Flood" ),
  ( "Flour" ),
  ( "Flower" ),
  ( "Flute" ),
  ( "Flying Fish" ),
  ( "Flying Squirrel" ),
  ( "Fog" ),
  ( "Force Knight" ),
  ( "Forest" ),
  ( "Fork" ),
  ( "Fortune Cookie" ),
  ( "Fossil" ),
  ( "Fountain" ),
  ( "Fountain of Youth" ),
  ( "Fox" ),
  ( "Frankenstein's Monster" ),
  ( "French Fries" ),
  ( "Fridge" ),
  ( "Frog" ),
  ( "Frozen Yogurt" ),
  ( "Fruit" ),
  ( "Fruit Tree" ),
  ( "Galaxy" ),
  ( "Galaxy Cluster" ),
  ( "Garage" ),
  ( "Garden" ),
  ( "Gardener" ),
  ( "Gargoyle" ),
  ( "Garuda" ),
  ( "Gas" ),
  ( "Gashadokuro" ),
  ( "Geyser" ),
  ( "Ghost" ),
  ( "Giant" ),
  ( "Gift" ),
  ( "Gingerbread House" ),
  ( "Gingerbread Man" ),
  ( "Glacier" ),
  ( "Glass" ),
  ( "Glasses" ),
  ( "Gnome" ),
  ( "Goat" ),
  ( "Goblin" ),
  ( "Gold" ),
  ( "Golem" ),
  ( "Granite" ),
  ( "Grass" ),
  ( "Grave" ),
  ( "Gravestone" ),
  ( "Graveyard" ),
  ( "Green Man" ),
  ( "Greenhouse" ),
  ( "Gremlin" ),
  ( "Grenade" ),
  ( "Griffin" ),
  ( "Grilled Cheese" ),
  ( "Grim Reaper" ),
  ( "Gun" ),
  ( "Gunpowder" ),
  ( "Gust" ),
  ( "Hacker" ),
  ( "Hail" ),
  ( "Ham" ),
  ( "Hamburger" ),
  ( "Hammer" ),
  ( "Hamster" ),
  ( "Hangar" ),
  ( "Harp" ),
  ( "Hay" ),
  ( "Hay Bale" ),
  ( "Heat" ),
  ( "Heaven" ),
  ( "Hedge" ),
  ( "Hedgehog" ),
  ( "Helicopter" ),
  ( "Hell" ),
  ( "Hellhound" ),
  ( "Hero" ),
  ( "Hill" ),
  ( "Hippo" ),
  ( "Holy Grail" ),
  ( "Holy Water" ),
  ( "Honey" ),
  ( "Horizon" ),
  ( "Horse" ),
  ( "Horseshoe" ),
  ( "Hospital" ),
  ( "Hot Chocolate" ),
  ( "Hourglass" ),
  ( "House" ),
  ( "Human" ),
  ( "Hummingbird" ),
  ( "Hurricane" ),
  ( "Husky" ),
  ( "Hydra" ),
  ( "Ice" ),
  ( "Ice Cream" ),
  ( "Ice Cream Truck" ),
  ( "Ice Sculpture" ),
  ( "Iceberg" ),
  ( "Iced Tea" ),
  ( "Idea" ),
  ( "Igloo" ),
  ( "Internet" ),
  ( "Island" ),
  ( "Ivy" ),
  ( "Jack O Lantern" ),
  ( "Jackalope" ),
  ( "Jam" ),
  ( "Jar" ),
  ( "Jerky" ),
  ( "Jiangshi" ),
  ( "Jormungandr" ),
  ( "Jotunn" ),
  ( "Juice" ),
  ( "Jupiter" ),
  ( "Kaiju" ),
  ( "Kanab" ),
  ( "Kappa" ),
  ( "Katana" ),
  ( "Kelpie" ),
  ( "Kite" ),
  ( "Kitsune" ),
  ( "Knife" ),
  ( "Knight" ),
  ( "Kraken" ),
  ( "Krampus" ),
  ( "Lake" ),
  ( "Lamp" ),
  ( "Land" ),
  ( "Laptop" ),
  ( "Lasso" ),
  ( "Lava" ),
  ( "Lava Lamp" ),
  ( "Lawn" ),
  ( "Lawn Mower" ),
  ( "Leaf" ),
  ( "Leather" ),
  ( "Legend" ),
  ( "Lens" ),
  ( "Letter" ),
  ( "Librarian" ),
  ( "Library" ),
  ( "Life" ),
  ( "Light Bulb" ),
  ( "Light Sword" ),
  ( "Lighthouse" ),
  ( "Lightning" ),
  ( "Lion" ),
  ( "Liquid" ),
  ( "Little Alchemy" ),
  ( "Livestock" ),
  ( "Lizard" ),
  ( "Log Cabin" ),
  ( "Love" ),
  ( "Lumberjack" ),
  ( "Maahes" ),
  ( "Mac and Cheese" ),
  ( "Machine" ),
  ( "Magic" ),
  ( "Magic Lamp" ),
  ( "Magma" ),
  ( "Mail Truck" ),
  ( "Mailbox" ),
  ( "Mailman" ),
  ( "Manatee" ),
  ( "Map" ),
  ( "Maple Syrup" ),
  ( "Mara" ),
  ( "Mars" ),
  ( "Marshmallows" ),
  ( "Maui" ),
  ( "Maui's Fishhook" ),
  ( "Mayonnaise" ),
  ( "Meat" ),
  ( "Medusa" ),
  ( "Mercury" ),
  ( "Mermaid" ),
  ( "Meteor" ),
  ( "Meteoroid" ),
  ( "Microscope" ),
  ( "Milk" ),
  ( "Milk Shake" ),
  ( "Mimic" ),
  ( "Mineral" ),
  ( "Minotaur" ),
  ( "Mirror" ),
  ( "Mist" ),
  ( "Mjolnir" ),
  ( "Mold" ),
  ( "Monarch" ),
  ( "Money" ),
  ( "Monkey" ),
  ( "Moon" ),
  ( "Moon Rover" ),
  ( "Moss" ),
  ( "Moth" ),
  ( "Mothman" ),
  ( "Motorcycle" ),
  ( "Mount Olympus" ),
  ( "Mountain" ),
  ( "Mountain Goat" ),
  ( "Mountain Range" ),
  ( "Mouse" ),
  ( "Mousetrap" ),
  ( "Mud" ),
  ( "Mummy" ),
  ( "Music" ),
  ( "Musician" ),
  ( "Narwhal" ),
  ( "Necromancer" ),
  ( "Necronomicon" ),
  ( "Needle" ),
  ( "Nessie" ),
  ( "Nest" ),
  ( "Net" ),
  ( "Newspaper" ),
  ( "Night" ),
  ( "Ninja" ),
  ( "Ninja Turtle" ),
  ( "Nuts" ),
  ( "Oasis" ),
  ( "Obsidian" ),
  ( "Ocean" ),
  ( "Oil" ),
  ( "Omelette" ),
  ( "Oni" ),
  ( "Ooze" ),
  ( "Optical Fiber" ),
  ( "Orc" ),
  ( "Orchard" ),
  ( "Ore" ),
  ( "Organic Matter" ),
  ( "Origami" ),
  ( "Ostrich" ),
  ( "Ouroboros" ),
  ( "Owl" ),
  ( "Oxygen" ),
  ( "Ozone" ),
  ( "Paint" ),
  ( "Painter" ),
  ( "Painting" ),
  ( "Paladin" ),
  ( "Paleontologist" ),
  ( "Palm" ),
  ( "Pan Flute" ),
  ( "Pandora's Box" ),
  ( "Paper" ),
  ( "Paper Airplane" ),
  ( "Paper Cup" ),
  ( "Parachute" ),
  ( "Paraglider" ),
  ( "Park" ),
  ( "Parrot" ),
  ( "Pasta" ),
  ( "Paul Bunyan" ),
  ( "Peach of Immortality" ),
  ( "Peacock" ),
  ( "Peanut Butter" ),
  ( "Peat" ),
  ( "Pebble" ),
  ( "Pegasus" ),
  ( "Pencil" ),
  ( "Pencil Sharpener" ),
  ( "Penguin" ),
  ( "Penicillin" ),
  ( "Perfume" ),
  ( "Petroleum" ),
  ( "Philosopher's Stone" ),
  ( "Phoenix" ),
  ( "Picnic" ),
  ( "Pie" ),
  ( "Pig" ),
  ( "Pigeon" ),
  ( "Piggy Bank" ),
  ( "Pilot" ),
  ( "Pinocchio" ),
  ( "Pipe" ),
  ( "Piranha" ),
  ( "Pirate" ),
  ( "Pirate Ship" ),
  ( "Pitchfork" ),
  ( "Pizza" ),
  ( "Planet" ),
  ( "Plankton" ),
  ( "Plant" ),
  ( "Plasma" ),
  ( "Platypus" ),
  ( "Plow" ),
  ( "Polar Bear" ),
  ( "Pollen" ),
  ( "Pond" ),
  ( "Popsicle" ),
  ( "Poseidon" ),
  ( "Post Office" ),
  ( "Potato" ),
  ( "Potter" ),
  ( "Pottery" ),
  ( "Pressure" ),
  ( "Primordial Soup" ),
  ( "Printer" ),
  ( "Prism" ),
  ( "Prometheus" ),
  ( "Pterodactyl" ),
  ( "Puddle" ),
  ( "Pumpkin" ),
  ( "Pyramid" ),
  ( "Quetzalcoatl" ),
  ( "Quicksand" ),
  ( "Quicksilver" ),
  ( "Ra" ),
  ( "Rabbit" ),
  ( "Rain" ),
  ( "Rainbow" ),
  ( "Rainbow Serpent" ),
  ( "Rainforest" ),
  ( "Rat" ),
  ( "Recipe" ),
  ( "Reed" ),
  ( "Reindeer" ),
  ( "Restaurant" ),
  ( "Ring" ),
  ( "River" ),
  ( "Rivulet" ),
  ( "Robot" ),
  ( "Robot Vacuum" ),
  ( "Roc" ),
  ( "Rock" ),
  ( "Rocket" ),
  ( "Roe" ),
  ( "Roller Coaster" ),
  ( "Rope" ),
  ( "Rose" ),
  ( "Ruins" ),
  ( "Ruler" ),
  ( "Rust" ),
  ( "Rv" ),
  ( "Sack" ),
  ( "Saddle" ),
  ( "Safe" ),
  ( "Safety Glasses" ),
  ( "Sailboat" ),
  ( "Sailor" ),
  ( "Salamander" ),
  ( "Salt" ),
  ( "Samurai" ),
  ( "Sand" ),
  ( "Sand Castle" ),
  ( "Sandman" ),
  ( "Sandpaper" ),
  ( "Sandstone" ),
  ( "Sandstorm" ),
  ( "Sandwich" ),
  ( "Santa" ),
  ( "Sap" ),
  ( "Saturn" ),
  ( "Scalpel" ),
  ( "Scarecrow" ),
  ( "Scissors" ),
  ( "Scorpion" ),
  ( "Scuba Tank" ),
  ( "Scythe" ),
  ( "Sea" ),
  ( "Seagull" ),
  ( "Seahorse" ),
  ( "Seal" ),
  ( "Seaplane" ),
  ( "Seasickness" ),
  ( "Seaweed" ),
  ( "Seed" ),
  ( "Selkie" ),
  ( "Sewing Machine" ),
  ( "Shark" ),
  ( "Sheep" ),
  ( "Sheet Music" ),
  ( "Shipwreck" ),
  ( "Shovel" ),
  ( "Shuriken" ),
  ( "Sickness" ),
  ( "Silo" ),
  ( "Skateboard" ),
  ( "Skeleton" ),
  ( "Ski Goggles" ),
  ( "Skier" ),
  ( "Sky" ),
  ( "Skyscraper" ),
  ( "Sleigh" ),
  ( "Sloth" ),
  ( "Smartphone" ),
  ( "Smog" ),
  ( "Smoke" ),
  ( "Smoke Signal" ),
  ( "Smoothie" ),
  ( "Snake" ),
  ( "Snow" ),
  ( "Snow Globe" ),
  ( "Snowball" ),
  ( "Snowboard" ),
  ( "Snowboarder" ),
  ( "Snowman" ),
  ( "Snowmobile" ),
  ( "Soap" ),
  ( "Soda" ),
  ( "Soil" ),
  ( "Solar Cell" ),
  ( "Solar System" ),
  ( "Solid" ),
  ( "Sound" ),
  ( "Space" ),
  ( "Space Station" ),
  ( "Spaceship" ),
  ( "Spaghetti" ),
  ( "Sphinx" ),
  ( "Spider" ),
  ( "Spoon" ),
  ( "Spotlight" ),
  ( "Sprinkles" ),
  ( "Squirrel" ),
  ( "Star" ),
  ( "Starfish" ),
  ( "Statue" ),
  ( "Steak" ),
  ( "Steam" ),
  ( "Steam Engine" ),
  ( "Steamboat" ),
  ( "Steel" ),
  ( "Steel Wool" ),
  ( "Stethoscope" ),
  ( "Stone" ),
  ( "Storm" ),
  ( "Story" ),
  ( "Stream" ),
  ( "String Phone" ),
  ( "Stun Gun" ),
  ( "Sugar" ),
  ( "Sun" ),
  ( "Sun Wukong" ),
  ( "Sundial" ),
  ( "Sunflower" ),
  ( "Sunglasses" ),
  ( "Supernova" ),
  ( "Surfer" ),
  ( "Sushi" ),
  ( "Swamp" ),
  ( "Sweater" ),
  ( "Swim Goggles" ),
  ( "Swimmer" ),
  ( "Swimming Pool" ),
  ( "Sword" ),
  ( "Swordfish" ),
  ( "Syringe" ),
  ( "Tablet" ),
  ( "Tailor" ),
  ( "Tank" ),
  ( "Tawaret" ),
  ( "Tea" ),
  ( "Telescope" ),
  ( "Tengu" ),
  ( "Tent" ),
  ( "The One Ring" ),
  ( "Thermometer" ),
  ( "Thor" ),
  ( "Thread" ),
  ( "Tide" ),
  ( "Titanic" ),
  ( "Toast" ),
  ( "Tobacco" ),
  ( "Tool" ),
  ( "Toolbox" ),
  ( "Tornado" ),
  ( "Toucan" ),
  ( "Tractor" ),
  ( "Train" ),
  ( "Trainyard" ),
  ( "Treasure" ),
  ( "Treasure Map" ),
  ( "Tree" ),
  ( "Treehouse" ),
  ( "Trojan Horse" ),
  ( "Troll" ),
  ( "Tsunami" ),
  ( "Tunnel" ),
  ( "Turtle" ),
  ( "Twilight" ),
  ( "Tyrannosaurus Rex" ),
  ( "Ufo" ),
  ( "Umbrella" ),
  ( "Unicorn" ),
  ( "Universe" ),
  ( "Vacuum Cleaner" ),
  ( "Valhalla" ),
  ( "Valkyrie" ),
  ( "Vampire" ),
  ( "Vase" ),
  ( "Vault" ),
  ( "Vegetable" ),
  ( "Venus" ),
  ( "Village" ),
  ( "Vine" ),
  ( "Vinegar" ),
  ( "Vodyanoy" ),
  ( "Volcano" ),
  ( "Vulcan" ),
  ( "Vulture" ),
  ( "Wagon" ),
  ( "Wall" ),
  ( "Wand" ),
  ( "Warmth" ),
  ( "Warrior" ),
  ( "Watch" ),
  ( "Water Gun" ),
  ( "Water Lily" ),
  ( "Water Pipe" ),
  ( "Waterfall" ),
  ( "Wave" ),
  ( "Wax" ),
  ( "Web" ),
  ( "Werewolf" ),
  ( "Wheat" ),
  ( "Wheel" ),
  ( "Wild Boar" ),
  ( "Will O' the Wisp" ),
  ( "Wind" ),
  ( "Wind Turbine" ),
  ( "Windmill" ),
  ( "Windsurfer" ),
  ( "Wine" ),
  ( "Wire" ),
  ( "Witch" ),
  ( "Wizard" ),
  ( "Wolf" ),
  ( "Wolpertinger" ),
  ( "Wood" ),
  ( "Woodpecker" ),
  ( "Wool" ),
  ( "World Turtle" ),
  ( "Wrapping Paper" ),
  ( "Writer" ),
  ( "Yeti" ),
  ( "Yggdrasil" ),
  ( "Yogurt" ),
  ( "Zeus" ),
  ( "Ziz" ),
  ( "Zombie" ),
  ( "Zoo"
;
