use v5.34;
use strict;
use warnings;
use Test::More;
use File::Temp qw(tempdir);
use lib 'lib';
use RPN;
use RPN::Graphics::Scene;
use RPN::Graphics::Shape;
use RPN::Matrix;
my $dir = tempdir(CLEANUP => 1);
local $ENV{RPN_HISTORY}="$dir/history"; local $ENV{RPN_STACKS}="$dir/stacks";
local $ENV{RPN_CONSTANTS}="$dir/constants"; local $ENV{RPN_VARIABLES}="$dir/variables";
local $ENV{RPN_FUNCTIONS}="$dir/functions"; local $ENV{RPN_CODEBLOCKS}="$dir/codeblocks";
my $c = RPN->new(install_dir => '.', no_readline => 1);
$c->process_input('320 200'); $c->process_input('scene');
$c->process_input('10 20 100 50'); $c->process_input('rectangle');
$c->process_input(q{'navy}); $c->process_input('strokecolor');
$c->process_input(q{'lightblue}); $c->process_input('fillcolor');
$c->process_input('draw');
ok(RPN::Graphics::Scene::is_scene($c->stack->peek), 'commands build scene');
$c->process_input('svg'); like($c->stack->pop, qr/fill="lightblue"/, 'svg renders styled scene');
$c->process_input('0 0 10 0'); $c->process_input('line');
$c->process_input('5 6'); $c->process_input('translate2d'); $c->process_input('transformshape');
ok(RPN::Graphics::Shape::is_shape($c->stack->pop), 'command transforms shape');
$c->stack->push(RPN::Matrix->new([0,0], [20,0], [10,15]));
$c->process_input('polygon');
is($c->stack->pop->type, 'polygon', 'polygon command accepts an Nx2 matrix');
$c->process_input('0 1 2'); $c->process_input('vec3');
$c->process_input('0 1 4'); $c->process_input('vec3'); $c->process_input('400 300'); $c->process_input('plot');
ok(RPN::Graphics::Scene::is_scene($c->stack->pop), 'plot command builds scene');
$c->process_input('-2 2 9 400 300'); $c->process_input('{ dup * }'); $c->process_input('functionplot');
ok(RPN::Graphics::Scene::is_scene($c->stack->pop), 'functionplot samples executable');
$c->process_input('qravailable'); like($c->stack->pop, qr/^[01]$/, 'QR availability is discoverable');
done_testing();
