UPDATE elements SET img="/icons/4.svg", description="A mixture of seemingly invisible gases that form Earth's atmosphere." WHERE element="air"
UPDATE elements SET img="/icons/607.svg", description="When small grows up." WHERE element="big"
UPDATE elements SET img="/icons/683.svg", description="Something used for holding or transporting stuff, like a box or one's mouth." WHERE element="container"
UPDATE elements SET img="/icons/3.svg", description="The land that makes up the third rock from the sun." WHERE element="earth"
UPDATE elements SET img="/icons/2.svg", description="Provider of warmth, light, and destruction." WHERE element="fire"
UPDATE elements SET img="/icons/122.svg", description="The universal illuminator." WHERE element="light"
UPDATE elements SET img="/icons/36.svg", description="The Wonder Material! Hard, soft, shiny, dull, liquid, solid; it can do it all!" WHERE element="metal"
UPDATE elements SET img="/icons/612.svg", description="When something or someone is moved or moving (physically, not emotionally)." WHERE element="motion"
UPDATE elements SET img="/icons/661.svg", description="The study of the fundamental nature of knowledge, reality, and existence of poultry." WHERE element="philosophy"
UPDATE elements SET img="/icons/619.svg", description="Any innocuous solid mineral, and when preceded by ""The,"" gains world-class acting and professional wrestling abilities." WHERE element="rock"
UPDATE elements SET img="/icons/659.svg", description="Systemic wonder applied to the natural world." WHERE element="science"
UPDATE elements SET img="/icons/616.svg", description="A size of lesser means. " WHERE element="small"
UPDATE elements SET img="/icons/747.svg", description="The result of a mad genius watching a mosquito bite them and thinking, ""I can do better!""" WHERE element="syringe"
UPDATE elements SET img="/icons/41.svg", description="THE FOURTH DIMENSION." WHERE element="time"
UPDATE elements SET img="/icons/742.svg", description="The answer for when someone asks you, ""Pickle me this?""" WHERE element="vinegar"
UPDATE elements SET img="/icons/1.svg", description="The All-Liquid." WHERE element="water"
UPDATE elements SET img="/icons/118.svg", description="The tragic result of a mad scientist's quest to conquer death" WHERE element="frankenstein's monster"
